---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.31"

availabilityZones:
  - "us-east-1a"
  - "us-east-1b"

iam:
  serviceRoleARN: arn:aws:iam::230247175281:role/LabRole

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.medium
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::230247175281:role/LabRole